version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
          - echo pre_build
  pre_build:
    commands:
      - echo pre_build
  build:
    commands:
      - mvn install
      - echo build
  post_build:
    commands:
      - echo post_build
      - mvn package
      - mv target/barksville.war barksville.war
artifacts:
  files:
    - barksville.war
    - .ebextensions/**/*
  base-directory: 'target/barksville'