version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
          - echo Nothing to do in the pre_build phase...
  pre_build:
    commands:
      - echo pre_build
  build:
    commands:
      - mvn install
      - echo build
  post_build:
    commands:
      - echo post_build
artifacts:
  files:
    - barksville-0.0.1-SNAPSHOT.war